name: Simple Prefix
main: com.flabaliki.simpleprefix.SimplePrefix
version: 2.2.1
author: Flabaliki
description: Easy prefixes & suffixes
website: http://dev.bukkit.org/server-mods/simple-prefix/
commands:
    spr:
        description: Multiple commands, use '/spr help' to see all.
        usage: "/spr help"